[2025-01-30T01:53:08.960+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T01:53:08.965+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2025-01-30T01:53:03.814300+00:00 [queued]>
[2025-01-30T01:53:08.967+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2025-01-30T01:53:03.814300+00:00 [queued]>
[2025-01-30T01:53:08.968+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T01:53:08.971+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2025-01-30 01:53:03.814300+00:00
[2025-01-30T01:53:08.974+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2352) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T01:53:08.975+0000] {standard_task_runner.py:72} INFO - Started process 2353 to run task
[2025-01-30T01:53:08.976+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'load_weather_data', 'manual__2025-01-30T01:53:03.814300+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp69zurosd']
[2025-01-30T01:53:08.976+0000] {standard_task_runner.py:105} INFO - Job 407: Subtask load_weather_data
[2025-01-30T01:53:08.992+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.load_weather_data manual__2025-01-30T01:53:03.814300+00:00 [running]> on host 10ad9b47e333
[2025-01-30T01:53:09.025+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T01:53:03.814300+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T01:53:03.814300+00:00'
[2025-01-30T01:53:09.025+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T01:53:09.026+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T01:53:09.026+0000] {logging_mixin.py:190} INFO - Current task name:load_weather_data state:running start_date:2025-01-30 01:53:08.965758+00:00
[2025-01-30T01:53:09.026+0000] {logging_mixin.py:190} INFO - Dag name:weather_etl_pipeline and current dag run status:running
[2025-01-30T01:53:09.026+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T01:53:09.029+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2025-01-30T01:53:09.035+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-30T01:53:09.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T01:53:09.039+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=load_weather_data, run_id=manual__2025-01-30T01:53:03.814300+00:00, execution_date=20250130T015303, start_date=20250130T015308, end_date=20250130T015309
[2025-01-30T01:53:09.043+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T01:53:09.043+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T01:53:09.043+0000] {logging_mixin.py:190} INFO - Dag name:weather_etl_pipeline queued_at:2025-01-30 01:53:03.873993+00:00
[2025-01-30T01:53:09.043+0000] {logging_mixin.py:190} INFO - Task hostname:10ad9b47e333 operator:_PythonDecoratedOperator
[2025-01-30T01:53:09.078+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T01:53:09.085+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T01:53:09.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
